//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull eclipse'
//
// Required dependencies: com.amplitude:java-sdk:[1.8.0,2.0), com.google.gson:gson
// Tracking Plan Version: 1
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/vaadin/IDE%20Plugins/implementation/eclipse)
//
package com.amplitude.ampli;

import java.lang.reflect.Method;
import java.util.HashMap;
import java.util.Map;

import com.amplitude.Amplitude;
import com.amplitude.MiddlewareExtra;
import com.amplitude.Plan;
import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.google.gson.JsonPrimitive;

public class Ampli {
    private static volatile Ampli singleton = null;

    public static Ampli getInstance() {
        if (singleton == null) {
            createSingleton();
        }
        return singleton;
    }

    private synchronized static void createSingleton() {
        if (singleton == null) {
            singleton = new Ampli();
        }
    }

    public enum Environment {
        IDEPLUGINS
    }

    public static final Map<Environment, String> API_KEY = new HashMap<>();

    static {
        API_KEY.put(Environment.IDEPLUGINS, "5332f8777b8ce7f12dcbf6c9d749488d");
    }

    private boolean disabled = false;

    public boolean isLoaded() {
        return this.client != null;
    }

    private Amplitude client;

    public Amplitude getClient() {
        this.isInitializedAndEnabled();
        return this.client;
    }

    private final Plan observePlan = new Plan().setBranch("main").setSource("eclipse").setVersion("1")
            .setVersionId("ac62c3f9-e92b-4502-8a50-3fd8f13c4103");

    // Options should have 'environment', 'client.api_key' or 'client.instance'
    public void load(LoadOptions options) {
        Boolean disabled = options.getDisabled();
        this.disabled = disabled != null ? disabled : false;

        if (this.isLoaded()) {
            System.err.println(
                    "Warning: Ampli is already initialized. Ampli.getInstance().load() should be called once at application start up.");
            return;
        }

        LoadClientOptions clientOptions = options.getClient();
        Environment env = options.getEnvironment();

        String apiKey = null;
        Amplitude client = null;

        if (clientOptions != null) {
            String optionsApiKey = clientOptions.getApiKey();
            if (optionsApiKey != null) {
                apiKey = optionsApiKey;
            }

            client = clientOptions.getInstance();
        } else if (env != null) {
            apiKey = Ampli.API_KEY.get(env);
        }

        if (client != null) {
            this.client = client;
        } else if (apiKey != null && !apiKey.equals("")) {
            this.client = Amplitude.getInstance();
            this.client.init(apiKey);
        } else {
            System.err.println(
                    "Ampli.getInstance().load() requires 'environment', 'client.apiKey', or 'client.instance'");
            return;
        }

        Plan plan = observePlan;
        if (clientOptions != null) {
            Plan optionsPlan = clientOptions.getPlan();
            if (optionsPlan != null) {
                plan = optionsPlan;
            }
        }
        this.client.setPlan(plan);

        // set IngestionMetadata with backwards compatibility, min Java SDK version
        // 1.10.1.
        try {
            Class<?> clazz = Class.forName("com.amplitude.IngestionMetadata");
            Method setSourceNameMethod = clazz.getMethod("setSourceName", String.class);
            Method setSourceVersionMethod = clazz.getMethod("setSourceVersion", String.class);
            Object ingestionMetadata = clazz.newInstance();
            setSourceNameMethod.invoke(ingestionMetadata, "jre-java-ampli");
            setSourceVersionMethod.invoke(ingestionMetadata, "1.0.0");
            Method setIngestionMetadata = Amplitude.class.getMethod("setIngestionMetadata", clazz);
            setIngestionMetadata.invoke(this.client, ingestionMetadata);
        } catch (ClassNotFoundException | NoSuchMethodException | SecurityException e) {
            System.out.println("com.amplitude.IngestionMetadata is available starting from Java SDK 1.10.1 version");
        } catch (Exception e) {
            System.err.println("Unexpected error when setting IngestionMetadata");
        }
    }

    public void track(String userId, Event event) {
        this.track(userId, event, null, null);
    }

    public void track(String userId, Event event, EventOptions options) {
        this.track(userId, event, options, null);
    }

    public void track(String userId, Event event, MiddlewareExtra extra) {
        this.track(userId, event, null, extra);
    }

    public void track(String userId, Event event, EventOptions options, MiddlewareExtra extra) {
        if (!this.isInitializedAndEnabled()) {
            return;
        }
        com.amplitude.Event amplitudeEvent = this.createAmplitudeEvent(event.eventType, options, userId);
        amplitudeEvent.eventProperties = this.getEventPropertiesJson(event);

        this.client.logEvent(amplitudeEvent, extra);
    }

    public void identify(String userId) {
        this.identify(userId, null, null);
    }

    public void identify(String userId, EventOptions options) {
        this.identify(userId, options, null);
    }

    public void identify(String userId, MiddlewareExtra extra) {
        this.identify(userId, null, extra);
    }

    public void identify(String userId, EventOptions options, MiddlewareExtra extra) {
        if (!this.isInitializedAndEnabled()) {
            return;
        }
        com.amplitude.Event amplitudeEvent = this.createAmplitudeEvent("Identify", options, userId);

        this.client.logEvent(amplitudeEvent, extra);
    }

    public void flush() {
        if (!this.isInitializedAndEnabled()) {
            return;
        }
        this.client.flushEvents();
    }

    /**
     * DebugWithHotswap
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/DebugWithHotswap">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     */
    public void debugWithHotswap(String userId, DebugWithHotswap event) {
        this.debugWithHotswap(userId, event, null, null);
    }

    /**
     * DebugWithHotswap
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/DebugWithHotswap">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     */
    public void debugWithHotswap(String userId, DebugWithHotswap event, EventOptions options) {
        this.debugWithHotswap(userId, event, options, null);
    }

    /**
     * DebugWithHotswap
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/DebugWithHotswap">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void debugWithHotswap(String userId, DebugWithHotswap event, MiddlewareExtra extra) {
        this.debugWithHotswap(userId, event, null, extra);
    }

    /**
     * DebugWithHotswap
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/DebugWithHotswap">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void debugWithHotswap(String userId, DebugWithHotswap event, EventOptions options, MiddlewareExtra extra) {
        this.track(userId, event, options, extra);
    }

    /**
     * ManualCopilotRestart
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ManualCopilotRestart">View in
     * Tracking Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     */
    public void manualCopilotRestart(String userId, ManualCopilotRestart event) {
        this.manualCopilotRestart(userId, event, null, null);
    }

    /**
     * ManualCopilotRestart
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ManualCopilotRestart">View in
     * Tracking Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     */
    public void manualCopilotRestart(String userId, ManualCopilotRestart event, EventOptions options) {
        this.manualCopilotRestart(userId, event, options, null);
    }

    /**
     * ManualCopilotRestart
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ManualCopilotRestart">View in
     * Tracking Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void manualCopilotRestart(String userId, ManualCopilotRestart event, MiddlewareExtra extra) {
        this.manualCopilotRestart(userId, event, null, extra);
    }

    /**
     * ManualCopilotRestart
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ManualCopilotRestart">View in
     * Tracking Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void manualCopilotRestart(String userId, ManualCopilotRestart event, EventOptions options,
            MiddlewareExtra extra) {
        this.track(userId, event, options, extra);
    }

    /**
     * PluginInitialized
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/PluginInitialized">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     */
    public void pluginInitialized(String userId, PluginInitialized event) {
        this.pluginInitialized(userId, event, null, null);
    }

    /**
     * PluginInitialized
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/PluginInitialized">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     */
    public void pluginInitialized(String userId, PluginInitialized event, EventOptions options) {
        this.pluginInitialized(userId, event, options, null);
    }

    /**
     * PluginInitialized
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/PluginInitialized">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void pluginInitialized(String userId, PluginInitialized event, MiddlewareExtra extra) {
        this.pluginInitialized(userId, event, null, extra);
    }

    /**
     * PluginInitialized
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/PluginInitialized">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void pluginInitialized(String userId, PluginInitialized event, EventOptions options, MiddlewareExtra extra) {
        this.track(userId, event, options, extra);
    }

    /**
     * ProjectCreated
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ProjectCreated">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     */
    public void projectCreated(String userId, ProjectCreated event) {
        this.projectCreated(userId, event, null, null);
    }

    /**
     * ProjectCreated
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ProjectCreated">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     */
    public void projectCreated(String userId, ProjectCreated event, EventOptions options) {
        this.projectCreated(userId, event, options, null);
    }

    /**
     * ProjectCreated
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ProjectCreated">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void projectCreated(String userId, ProjectCreated event, MiddlewareExtra extra) {
        this.projectCreated(userId, event, null, extra);
    }

    /**
     * ProjectCreated
     * <p>
     * <a href= "https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest/ProjectCreated">View in Tracking
     * Plan</a>
     * <p>
     * Event has no description in tracking plan.
     *
     * @param userId
     *            The user's ID
     * @param event
     *            The event
     * @param options
     *            The event's options
     * @param extra
     *            Extra untyped parameters for use in middleware
     */
    public void projectCreated(String userId, ProjectCreated event, EventOptions options, MiddlewareExtra extra) {
        this.track(userId, event, options, extra);
    }

    private com.amplitude.Event createAmplitudeEvent(String eventType, EventOptions options, String userId) {
        com.amplitude.Event event = new com.amplitude.Event(eventType,
                userId != null ? userId : (options != null ? options.userId : null),
                options != null ? options.deviceId : null);
        if (options != null && options.timestamp != null) {
            event.timestamp = options.timestamp;
        }
        if (options != null && options.locationLat != null) {
            event.locationLat = options.locationLat;
        }
        if (options != null && options.locationLng != null) {
            event.locationLng = options.locationLng;
        }
        if (options != null && options.appVersion != null) {
            event.appVersion = options.appVersion;
        }
        if (options != null && options.versionName != null) {
            event.versionName = options.versionName;
        }
        if (options != null && options.platform != null) {
            event.platform = options.platform;
        }
        if (options != null && options.osName != null) {
            event.osName = options.osName;
        }
        if (options != null && options.osVersion != null) {
            event.osVersion = options.osVersion;
        }
        if (options != null && options.deviceBrand != null) {
            event.deviceBrand = options.deviceBrand;
        }
        if (options != null && options.deviceManufacturer != null) {
            event.deviceManufacturer = options.deviceManufacturer;
        }
        if (options != null && options.deviceModel != null) {
            event.deviceModel = options.deviceModel;
        }
        if (options != null && options.carrier != null) {
            event.carrier = options.carrier;
        }
        if (options != null && options.country != null) {
            event.country = options.country;
        }
        if (options != null && options.region != null) {
            event.region = options.region;
        }
        if (options != null && options.city != null) {
            event.city = options.city;
        }
        if (options != null && options.dma != null) {
            event.dma = options.dma;
        }
        if (options != null && options.idfa != null) {
            event.idfa = options.idfa;
        }
        if (options != null && options.idfv != null) {
            event.idfv = options.idfv;
        }
        if (options != null && options.adid != null) {
            event.adid = options.adid;
        }
        if (options != null && options.androidId != null) {
            event.androidId = options.androidId;
        }
        if (options != null && options.language != null) {
            event.language = options.language;
        }
        if (options != null && options.partnerId != null) {
            event.partnerId = options.partnerId;
        }
        if (options != null && options.ip != null) {
            event.ip = options.ip;
        }
        if (options != null && options.price != null) {
            event.price = options.price;
        }
        if (options != null && options.quantity != null) {
            event.quantity = options.quantity;
        }
        if (options != null && options.revenue != null) {
            event.revenue = options.revenue;
        }
        if (options != null && options.productId != null) {
            event.productId = options.productId;
        }
        if (options != null && options.revenueType != null) {
            event.revenueType = options.revenueType;
        }
        if (options != null && options.eventId != null) {
            event.eventId = options.eventId;
        }
        if (options != null && options.sessionId != null) {
            event.sessionId = options.sessionId;
        }
        if (options != null && options.insertId != null) {
            event.insertId = options.insertId;
        }
        if (options != null && options.plan != null) {
            event.plan = options.plan;
        }
        return event;
    }

    private boolean isInitializedAndEnabled() {
        if (!this.isLoaded()) {
            System.err.println(
                    "Ampli is not yet initialized. Have you called `Ampli.getInstance().load()` on app start?");
            return false;
        }
        return !this.disabled;
    }

    private JsonObject getEventPropertiesJson(Event event) {
        if (event == null || event.eventProperties == null) {
            return null;
        }

        JsonObject json = new JsonObject();

        for (Map.Entry<String, Object> entry : event.eventProperties.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();
            try {
                if (value != null) {
                    if (value.getClass().isArray()) {
                        // Handle arrays by converting to JsonArray
                        JsonArray jsonArray = new JsonArray();
                        Object[] array = (Object[]) value;
                        for (Object item : array) {
                            if (item instanceof String) {
                                jsonArray.add(new JsonPrimitive((String) item));
                            } else if (item instanceof Number) {
                                jsonArray.add(new JsonPrimitive((Number) item));
                            } else if (item instanceof Boolean) {
                                jsonArray.add(new JsonPrimitive((Boolean) item));
                            } else {
                                jsonArray.add(new JsonPrimitive(item.toString()));
                            }
                        }
                        json.add(key, jsonArray);
                    } else if (value instanceof String) {
                        json.addProperty(key, (String) value);
                    } else if (value instanceof Number) {
                        json.addProperty(key, (Number) value);
                    } else if (value instanceof Boolean) {
                        json.addProperty(key, (Boolean) value);
                    } else {
                        json.addProperty(key, value.toString());
                    }
                } else {
                    json.add(key, null);
                }
            } catch (Exception e) {
                System.err.printf("Error converting properties to JsonObject: %s%n", e.getMessage());
            }
        }

        return json;
    }
}
