//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull eclipse'
//
// Required dependencies: com.amplitude:java-sdk:[1.8.0,2.0), com.google.gson:gson
// Tracking Plan Version: 1
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/vaadin/IDE%20Plugins/implementation/eclipse)
//
package com.amplitude.ampli;

import java.util.Map;

public abstract class Event {
    final String eventType;
    final Map<String, Object> eventProperties;

    protected Event(String eventType, Map<String, Object> eventProperties) {
        this.eventType = eventType;
        this.eventProperties = eventProperties == null || eventProperties.isEmpty() ? null : eventProperties;
    }
}
