//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull eclipse'
//
// Required dependencies: com.amplitude:java-sdk:[1.8.0,2.0), com.google.gson:gson
// Tracking Plan Version: 1
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/vaadin/IDE%20Plugins/implementation/eclipse)
//
package com.amplitude.ampli;

import com.amplitude.Plan;

public class EventOptions {
    String userId;
    String deviceId;
    Long timestamp;
    Double locationLat;
    Double locationLng;
    String appVersion;
    String versionName;
    String platform;
    String osName;
    String osVersion;
    String deviceBrand;
    String deviceManufacturer;
    String deviceModel;
    String carrier;
    String country;
    String region;
    String city;
    String dma;
    String idfa;
    String idfv;
    String adid;
    String androidId;
    String language;
    String partnerId;
    String ip;
    Double price;
    Integer quantity;
    Double revenue;
    String productId;
    String revenueType;
    Integer eventId;
    Long sessionId;
    String insertId;
    Plan plan;

    public EventOptions setUserId(String userId) {
        this.userId = userId;
        return this;
    }

    public EventOptions setDeviceId(String deviceId) {
        this.deviceId = deviceId;
        return this;
    }

    public EventOptions setTimestamp(Long timestamp) {
        this.timestamp = timestamp;
        return this;
    }

    public EventOptions setLocationLat(Double locationLat) {
        this.locationLat = locationLat;
        return this;
    }

    public EventOptions setLocationLng(Double locationLng) {
        this.locationLng = locationLng;
        return this;
    }

    public EventOptions setAppVersion(String appVersion) {
        this.appVersion = appVersion;
        return this;
    }

    public EventOptions setVersionName(String versionName) {
        this.versionName = versionName;
        return this;
    }

    public EventOptions setPlatform(String platform) {
        this.platform = platform;
        return this;
    }

    public EventOptions setOsName(String osName) {
        this.osName = osName;
        return this;
    }

    public EventOptions setOsVersion(String osVersion) {
        this.osVersion = osVersion;
        return this;
    }

    public EventOptions setDeviceBrand(String deviceBrand) {
        this.deviceBrand = deviceBrand;
        return this;
    }

    public EventOptions setDeviceManufacturer(String deviceManufacturer) {
        this.deviceManufacturer = deviceManufacturer;
        return this;
    }

    public EventOptions setDeviceModel(String deviceModel) {
        this.deviceModel = deviceModel;
        return this;
    }

    public EventOptions setCarrier(String carrier) {
        this.carrier = carrier;
        return this;
    }

    public EventOptions setCountry(String country) {
        this.country = country;
        return this;
    }

    public EventOptions setRegion(String region) {
        this.region = region;
        return this;
    }

    public EventOptions setCity(String city) {
        this.city = city;
        return this;
    }

    public EventOptions setDma(String dma) {
        this.dma = dma;
        return this;
    }

    public EventOptions setIdfa(String idfa) {
        this.idfa = idfa;
        return this;
    }

    public EventOptions setIdfv(String idfv) {
        this.idfv = idfv;
        return this;
    }

    public EventOptions setAdid(String adid) {
        this.adid = adid;
        return this;
    }

    public EventOptions setAndroidId(String androidId) {
        this.androidId = androidId;
        return this;
    }

    public EventOptions setLanguage(String language) {
        this.language = language;
        return this;
    }

    public EventOptions setPartnerId(String partnerId) {
        this.partnerId = partnerId;
        return this;
    }

    public EventOptions setIp(String ip) {
        this.ip = ip;
        return this;
    }

    public EventOptions setPrice(Double price) {
        this.price = price;
        return this;
    }

    public EventOptions setQuantity(Integer quantity) {
        this.quantity = quantity;
        return this;
    }

    public EventOptions setRevenue(Double revenue) {
        this.revenue = revenue;
        return this;
    }

    public EventOptions setProductId(String productId) {
        this.productId = productId;
        return this;
    }

    public EventOptions setRevenueType(String revenueType) {
        this.revenueType = revenueType;
        return this;
    }

    public EventOptions setEventId(Integer eventId) {
        this.eventId = eventId;
        return this;
    }

    public EventOptions setSessionId(Long sessionId) {
        this.sessionId = sessionId;
        return this;
    }

    public EventOptions setInsertId(String insertId) {
        this.insertId = insertId;
        return this;
    }

    public EventOptions setPlan(Plan plan) {
        this.plan = plan;
        return this;
    }
}
