//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull eclipse'
//
// Required dependencies: com.amplitude:java-sdk:[1.8.0,2.0), com.google.gson:gson
// Tracking Plan Version: 1
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/vaadin/IDE%20Plugins/implementation/eclipse)
//
package com.amplitude.ampli;

import java.util.HashMap;

public class Identify extends Event {
    private Identify(Builder builder) {
        super("Identify", builder.properties);
    }

    public static IBuild builder() {
        return new Builder();
    }

    // Inner Builder class with required properties
    public static class Builder implements IBuild {
        private final HashMap<String, Object> properties = new HashMap<>();

        private Builder() {

        }

        public Identify build() {
            return new Identify(this);
        }
    }

    /** Build interface with optional properties */
    public interface IBuild {
        Identify build();
    }
}
