//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull eclipse'
//
// Required dependencies: com.amplitude:java-sdk:[1.8.0,2.0), org.json:json:20201115
// Tracking Plan Version: 1
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/vaadin/IDE%20Plugins/implementation/eclipse)
//
package com.amplitude.ampli;

import com.amplitude.Amplitude;
import com.amplitude.Plan;

public class LoadClientOptions {
    private String apiKey;
    private Amplitude instance;
    private Plan plan;

    public LoadClientOptions() {
    }

    public LoadClientOptions setApiKey(String apiKey) {
        this.apiKey = apiKey;
        return this;
    }

    public String getApiKey() {
        return this.apiKey;
    }

    public LoadClientOptions setInstance(Amplitude instance) {
        this.instance = instance;
        return this;
    }

    public Amplitude getInstance() {
        return this.instance;
    }

    public LoadClientOptions setPlan(Plan plan) {
        this.plan = plan;
        return this;
    }

    public Plan getPlan() {
        return this.plan;
    }
}
