//
// Ampli - A strong typed wrapper for your Analytics
//
// This file is generated by Amplitude.
// To update run 'ampli pull eclipse'
//
// Required dependencies: com.amplitude:java-sdk:[1.8.0,2.0), org.json:json:20201115
// Tracking Plan Version: 1
// Build: 1.0.0
// Runtime: jre:java-ampli
//
// [View Tracking Plan](https://data.amplitude.com/vaadin/IDE%20Plugins/events/main/latest)
//
// [Full Setup Instructions](https://data.amplitude.com/vaadin/IDE%20Plugins/implementation/eclipse)
//
package com.amplitude.ampli;

import java.util.HashMap;

public class ProjectCreated extends Event {
    private ProjectCreated(Builder builder) {
        super("ProjectCreated", builder.properties);
    }

    public static IVaadiner builder() { return new Builder(); }

    // Inner Builder class with required properties
    public static class Builder implements IVaadiner, IBuild {
        private final HashMap<String, Object> properties = new HashMap<>();

        private Builder() {

        }

        /**

         * <p>
         * Must be followed by by additional optional properties or build() method
         */
        public IBuild vaadiner(boolean vaadiner) {
            this.properties.put("Vaadiner", vaadiner);
            return this;
        }

        /**

         */
        public IBuild downloadUrl(String downloadUrl) {
            this.properties.put("downloadUrl", downloadUrl);
            return this;
        }

        public ProjectCreated build() {
            return new ProjectCreated(this);
        }
    }

    // Required property interfaces
    public interface IVaadiner {
        IBuild vaadiner(boolean vaadiner);
    }

    /** Build interface with optional properties */
    public interface IBuild {
        IBuild downloadUrl(String downloadUrl);
        ProjectCreated build();
    }
}
