package com.vaadin.integration.eclipse.maven;
import java.io.File;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Set;

import org.apache.maven.model.Build;
import org.apache.maven.model.Resource;
import org.apache.maven.plugin.MojoExecution;
import org.apache.maven.project.MavenProject;
import org.codehaus.plexus.util.Scanner;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.CoreException;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.m2e.core.MavenPlugin;
import org.eclipse.m2e.core.embedder.IMaven;
import org.eclipse.m2e.core.project.configurator.MojoExecutionBuildParticipant;
import org.sonatype.plexus.build.incremental.BuildContext;

public class VaadinMojoExecutionBuildParticipant
    extends MojoExecutionBuildParticipant
{
    private static final IMaven maven = MavenPlugin.getMaven();

    public VaadinMojoExecutionBuildParticipant( MojoExecution execution )
    {
        super( execution, true );
    }

    @Override
    public Set<IProject> build( int kind, IProgressMonitor monitor )
        throws Exception
    {
        BuildContext buildContext = getBuildContext();

        // skip executing the goal if no relevant files have changed
        if (!appliesToGoal(buildContext, monitor)) {
            return null;
        }

        // execute mojo
        Set<IProject> result = super.build(kind, monitor);

        // refresh files generated by the mojo
        refreshTarget(buildContext, monitor);

        return result;
    }

    private boolean appliesToGoal(BuildContext buildContext,
            IProgressMonitor monitor) throws CoreException {
        if (isGoal("update-theme") || isGoal("compile-theme")) {
            for (File themeDir : getThemeDirectories(monitor)) {
                if (themeDir.exists() && scanDirectory(buildContext, themeDir)) {
                    return true;
                }
            }
            return false;
        }

        // no changes that we know should trigger a build => don't trigger one
        return false;
    }

    private boolean scanDirectory(BuildContext buildContext, File source) {
        // scan the source directory for applicable files
        Scanner ds = buildContext.newScanner(source); // delta or full
        ds.scan();
        String[] includedFiles = ds.getIncludedFiles();
        if (includedFiles == null || includedFiles.length <= 0) {
            return false;
        }
        return true;
    }

    private boolean isGoal(String goal) {
        return goal.equals(getMojoExecution().getGoal());
    }

    private void refreshTarget(BuildContext buildContext,
            IProgressMonitor monitor)
            throws CoreException {
        if (isGoal("update-theme") || isGoal("compile-theme")) {
            for (File themeDir : getThemeDirectories(monitor)) {
                if (themeDir.exists()) {
                    buildContext.refresh(themeDir);
                }
            }
        }
    }

    private Collection<File> getThemeDirectories(IProgressMonitor monitor)
            throws CoreException {
        ArrayList<File> result = new ArrayList<File>();

        MavenProject project = getMavenProject(monitor);
        File basedir = project.getBasedir();
        Build build = project.getBuild();

        result.add(new File(basedir, "src/main/webapp/VAADIN/themes"));
        for (Resource resource : build.getResources()) {
            result.add(new File(resource.getDirectory(), "VAADIN/themes"));
        }
        result.add(new File(build.getSourceDirectory(), "VAADIN/themes"));

        return result;
    }

    private MavenProject getMavenProject(IProgressMonitor monitor)
            throws CoreException {
        return getMavenProjectFacade().getMavenProject( monitor );
    }
}
