name: Build

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
      
      - name: Cache Tycho/P2 dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository/.cache/tycho
          key: ${{ runner.os }}-tycho-${{ hashFiles('**/pom.xml', '**/MANIFEST.MF', '**/feature.xml', '**/category.xml') }}
          restore-keys: |
            ${{ runner.os }}-tycho-
      
      - name: Build and Test with Maven
        run: mvn -B verify
